### ISSUE TITLE
Testnet Faucet has been returning 502 Bad Gateway for 3 days now

### ISSUE THREAD

**Issue by d-sfounis** [Bytom/faucet#1]
Hi,
Check out http://test.blockmeta.com/faucet.php
It has been down for days

**Comment by zruijie** [comment]
Hi, http://test.blockmeta.com/faucet.php had been shut down several days ago. Now, you can get testnet coins from new page: https://blockmeta.com/tools/faucet.

You just fill your testnet address:

![image](https://user-images.githubusercontent.com/17916496/56047799-ce4b2280-5d78-11e9-8bf8-51e3f32215aa.png)

 then tx id will be return:

![image](https://user-images.githubusercontent.com/17916496/56047823-dc00a800-5d78-11e9-9659-6e37147c38e8.png)

**Comment by d-sfounis** [comment]
Hey, thanks!

You should probably update the GitHub description, as you still have the old links, and this GitHub page is the first result when someone searches for "BYTOM faucet"

**Comment by zruijie** [comment]
Another way to get testnet coin is post your receiver address to https://kit.blockmeta.com/api/v1/get_testnet_coins: 
![image](https://user-images.githubusercontent.com/17916496/56048601-70b7d580-5d7a-11e9-8284-407282ff8bc0.png)

**Comment by zruijie** [comment]
@Agouri Thank you for your tips, I will update the description.

**Comment by d-sfounis** [comment]
No provlem, thank YOU for replying so quickly.

Closing the issue. Have a good weekend.
